// Mock data and templates for YouTube Live Control Tower

export const THUMBNAIL_TEMPLATES = [
  {
    id: 'midnight_navy',
    name: '미드나잇 네이비 (모던 클래식)',
    bgType: 'gradient',
    bgGradient: {
      from: '#0f172a',
      to: '#1e1b4b',
      angle: 135,
    },
    titleColor: '#ffffff',
    subtitleColor: '#93c5fd',
    badgeBg: '#ef4444',
    badgeText: '#ffffff',
    accentColor: '#38bdf8',
    category: 'worship',
  },
  {
    id: 'burgundy_wine',
    name: '버건디 와인 (경건한 예배)',
    bgType: 'gradient',
    bgGradient: {
      from: '#450a0a',
      to: '#1c1917',
      angle: 150,
    },
    titleColor: '#fef08a',
    subtitleColor: '#fecaca',
    badgeBg: '#dc2626',
    badgeText: '#ffffff',
    accentColor: '#fbbf24',
    category: 'worship',
  },
  {
    id: 'deep_purple',
    name: '딥 퍼플 글로우 (찬양/성령집회)',
    bgType: 'gradient',
    bgGradient: {
      from: '#3b0764',
      to: '#09090b',
      angle: 120,
    },
    titleColor: '#ffffff',
    subtitleColor: '#e9d5ff',
    badgeBg: '#a855f7',
    badgeText: '#ffffff',
    accentColor: '#c084fc',
    category: 'event',
  },
  {
    id: 'gold_amber',
    name: '골드 앰버 (특별행사/기념)',
    bgType: 'gradient',
    bgGradient: {
      from: '#78350f',
      to: '#18181b',
      angle: 135,
    },
    titleColor: '#fef3c7',
    subtitleColor: '#fde68a',
    badgeBg: '#f59e0b',
    badgeText: '#000000',
    accentColor: '#fbbf24',
    category: 'special',
  },
  {
    id: 'emerald_peace',
    name: '에메랄드 숲 (청년/힐링)',
    bgType: 'gradient',
    bgGradient: {
      from: '#064e3b',
      to: '#022c22',
      angle: 140,
    },
    titleColor: '#ffffff',
    subtitleColor: '#a7f3d0',
    badgeBg: '#10b981',
    badgeText: '#ffffff',
    accentColor: '#34d399',
    category: 'youth',
  },
  {
    id: 'clean_dark',
    name: '미니멀 옵시디언 (심플 블랙)',
    bgType: 'gradient',
    bgGradient: {
      from: '#18181b',
      to: '#09090b',
      angle: 180,
    },
    titleColor: '#ffffff',
    subtitleColor: '#a1a1aa',
    badgeBg: '#e11d48',
    badgeText: '#ffffff',
    accentColor: '#f43f5e',
    category: 'minimal',
  },
];

export const INITIAL_MOCK_BROADCASTS = [
  {
    id: 'yt_live_demo_001',
    title: '[2026.09.20] 주일 대예배 실시간 생중계 - "은혜의 강가로 나아가라"',
    description: `2026년 9월 20일 주일 대예배 실시간 온라인 생중계
말씀: 에스겔 47:1-12
설교: 김요한 담임목사
온라인으로 참여하시는 모든 성도님들을 환영하고 축복합니다.`,
    status: 'ready', // 'ready' (upcoming/scheduled), 'live' (active), 'complete' (ended)
    scheduledStartTime: new Date(Date.now() + 1000 * 60 * 45).toISOString(), // 45 minutes later
    actualStartTime: null,
    actualEndTime: null,
    privacyStatus: 'public',
    viewerCount: 0,
    likeCount: 0,
    streamHealth: 'good',
    latency: 'ultraLow',
    thumbnailUrl: '',
    streamKey: 'rtmp-live-stream-key-demo-001',
    rtmpUrl: 'rtmp://a.rtmp.youtube.com/live2',
    channelTitle: '미라클 스튜디오 TV',
  },
  {
    id: 'yt_live_demo_002',
    title: '[2026.09.18] 금요 심야 성령대망 찬양집회 LIVE',
    description: `금요 심야 성령집회 실시간 중계 녹화본입니다.
찬양과 기도로 회복되는 은혜의 시간.`,
    status: 'complete',
    scheduledStartTime: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    actualStartTime: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    actualEndTime: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    privacyStatus: 'public',
    viewerCount: 412,
    likeCount: 89,
    streamHealth: 'good',
    latency: 'ultraLow',
    thumbnailUrl: '',
    streamKey: 'rtmp-live-stream-key-demo-002',
    rtmpUrl: 'rtmp://a.rtmp.youtube.com/live2',
    channelTitle: '미라클 스튜디오 TV',
  },
  {
    id: 'yt_live_demo_003',
    title: '[2026.09.16] 수요 성경강해 - "로마서에 나타난 하나님의 의"',
    description: `수요 성경강해 라이브 방송 아카이브입니다.
강해: 박준석 목사`,
    status: 'complete',
    scheduledStartTime: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    actualStartTime: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    actualEndTime: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
    privacyStatus: 'public',
    viewerCount: 285,
    likeCount: 54,
    streamHealth: 'good',
    latency: 'ultraLow',
    thumbnailUrl: '',
    streamKey: 'rtmp-live-stream-key-demo-003',
    rtmpUrl: 'rtmp://a.rtmp.youtube.com/live2',
    channelTitle: '미라클 스튜디오 TV',
  },
];

export const MOCK_CHAT_MESSAGES = [
  { id: '1', user: '은혜맘', message: '할렐루야! 오늘도 집에서 가족들과 함께 예배드립니다 🙏', time: '11:02' },
  { id: '2', user: '박권사', message: '목사님 음성과 화면 모두 아주 깨끗하게 잘 나옵니다.', time: '11:03' },
  { id: '3', user: 'David_Lee', message: '아멘! 은혜의 강가로 나아가길 소망합니다!', time: '11:04' },
  { id: '4', user: '미라클찬양팀', message: '성도님들 환영합니다! 예배 중 소리가 작으시면 볼륨을 확인해주세요.', time: '11:05', isModerator: true },
  { id: '5', user: '수원_김집사', message: '아멘 아멘! 귀한 말씀 감사합니다.', time: '11:08' },
  { id: '6', user: 'Grace_Kim', message: '기도로 동역합니다. 축복합니다~ ❤️', time: '11:10' },
];
